add_rules("mode.debug", "mode.release")

target("spmv")
    set_kind("binary")
    add_files("src/*.cpp")
    add_files("src/*.cu")
    set_languages("c++17")
    add_cuflags("-std=c++17", {force = true})
    add_cuflags("-rdc=true", {force = true})
    add_culdflags("-rdc=true", {force = true})
    --Force ampere for dev only
    --add_cugencodes("sm_80")
    add_includedirs("inc/")
    add_headerfiles("inc/*.h", "inc/*.cuh")
    add_cxflags("-fopenmp")
    add_ldflags("-fopenmp")
    add_syslinks("cusparse")